branches:
  only:
    - develop
    - master
      
# Do not build on tags
skip_tags: true

clone_folder: c:\projects\testify

configuration: Release

environment:
  GitHubPersonalAccessToken:
    secure: H9H2HNKz0vEz91m6b5aEoEeb3xhrI3rbsJKvmbkQFbwq0P+zqhoPdcx4EBqNbvYl

install:
  - ps: .\build_scripts\install.ps1 $env:APPVEYOR_BUILD_FOLDER

before_build:
  - ps: nuget restore

build:
  project: Testify.sln
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true

after_test:
  - ps: .\build_scripts\push_pages.ps1 -BuildFolder $env:APPVEYOR_BUILD_FOLDER -Username wekempf -Email wekempf@outlook.com -PersonalAccessToken $env:GitHubPersonalAccessToken

artifacts:
  - path: 'docs\site.zip'

deploy:
- provider: NuGet
  server: https://www.myget.org/F/wekempf/api/v2
  api_key:
    secure: 3bjCk3g3eDsa72b1jJR9QRWK+iivJLfcNVBV/fVJChIwtBdZxTKOrBZxhOHU5jR/
  skip_symbols: true
  artifacts: /src\\.*\.nupkg/
  on:
    branch: develop
- provider: NuGet
  api_key:
    secure: #WCC9YoXjXGB6om2aN3jD0n5Jk63LKg42sViodxTK04T16/MQ0e4F8JU2XmoO+iY6
  skip_symbols: false
  artifacts: /src\\.*\.nupkg/
  on:
    branch: master
